#!/bin/bash
unset _JAVA_OPTIONS JAVA_TOOL_OPTIONS JAVA_OPTS GRADLE_OPTS
unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY no_proxy NO_PROXY
exec env -i \
  HOME="$HOME" \
  PATH="$PATH" \
  LANG="$LANG" \
  USER="$USER" \
  LOGNAME="$LOGNAME" \
  SHELL="$SHELL" \
  PWD="$PWD" \
  XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
  DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" \
  DISPLAY="$DISPLAY" \
  WAYLAND_DISPLAY="$WAYLAND_DISPLAY" \
  XDG_SESSION_TYPE="$XDG_SESSION_TYPE" \
  XDG_CURRENT_DESKTOP="$XDG_CURRENT_DESKTOP" \
  "$@"
