# Generated by Django 5.2.16 on 2026-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('traffic_bytes', models.BigIntegerField(help_text='Total traffic quota in bytes')),
                ('price_toman', models.PositiveIntegerField(help_text='Price in Toman')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in plan listing')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Key-value feature list')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'price_toman'),
            },
        ),
    ]
