# Generated by Django 5.2.16 on 2026-07-10 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('traffic_exhausted', 'Traffic Exhausted'), ('cancelled', 'Cancelled'), ('pending', 'Pending Activation')], default='pending', max_length=20)),
                ('title', models.CharField(help_text='User-given label for this subscription', max_length=30)),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', help_text='Android device unique ID for free plan tracking', max_length=64)),
                ('total_traffic_byte', models.BigIntegerField(help_text='Total quota in bytes')),
                ('total_traffic_usage_byte', models.BigIntegerField(default=0, help_text='Used traffic in bytes')),
                ('traffic_is_over', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['username'], name='subscriptio_usernam_7d6b79_idx'), models.Index(fields=['device_id', 'plan'], name='subscriptio_device__53857e_idx')],
            },
        ),
    ]
