# Generated by Django 5.2.16 on 2026-07-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_toman', models.PositiveIntegerField(help_text='Amount in Toman')),
                ('gateway', models.CharField(choices=[('cafebazar', 'Cafe Bazar')], default='cafebazar', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchase_token', models.CharField(blank=True, default='', help_text='Cafe Bazar purchase token', max_length=512)),
                ('product_id', models.CharField(blank=True, default='', help_text='Cafe Bazar product SKU', max_length=200)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'), models.Index(fields=['purchase_token'], name='payments_pa_purchas_f50430_idx')],
            },
        ),
    ]
